### ISSUE TITLE
Should c-panel stretch to height of its content or remain at fixed height of viewport?

### ISSUE THREAD

**Issue by rowlando** [sky-uk/toolkit-ui#109]
**Details of the Toolkit version you're using**
toolkit-core v0.3.15
toolkit-ui v0.3.0

**Details of the problem and what you're expecting to be the solution.**
The Sky homepage uses the panel pattern extensively but doesn't set a max-height equal to the viewport. The panels on Sky.com are revealed programmatically with JavaScript, not CSS transitions.

The panel component in toolkit-ui sets a `max-height: 100vh`.

We don't know what problem the panel, from a UX perspective, is trying to solve, so are unsure whether (A) the panel should stretch to height of its content or (B) whether the panel is only ever intended to work with content that fits in the height of the viewport.

For our current use-case, we've been given a design that falls into (A). We haven't found a fix yet.

Can you let us know if the panel will work as A in the future?

**Link to / screenshot of the problem.**
To recreate the problem:

1. go to the [panel](http://sky-uk.github.io/toolkit/#ui-tiles)
2. add content to the panel to increase the height to more than the viewport
3. close / reveal the panel by adding the `is-open` class to `c-panel` div.

**Links to / comment code blocks of your Markup.**
We've tried creating a custom modifier for the panel, ie:

```css
.c-panel--no-max-height.is-open {
  max-height: auto;
}
```
This results in the transition not taking place.

A quick Google reveals that there's no current way to transition from auto to a fixed height.

**Comment by joebell93** [comment]
@rowlando I think having a panel that fits to the content size seems like a sensible idea. I imagine we'd follow something similar to the way we handle it in `c-hero` and use a class like `c-panel--fit-content`.

Unfortunately, you're right though - height would have to be detected in JavaScript to animate.

I'll bring this up with the design team and get back to you on what the appropriate size should be. Either way, I imagine we'll have modifiers in place, and we'll implement these soon.

(P.S thanks for the really detailed issue description!)

**Comment by joebell93** [comment]
Including in https://github.com/sky-uk/toolkit-ui/issues/174
