### ISSUE TITLE
Add gradient keyline variant

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#113]
Requirement from design

<img src='https://s32.postimg.org/n2b558wz9/Screen_Shot_2016_07_20_at_13_42_45.png' border='0' alt='Gradient Keyline'/>

**Comment by aaronthomas** [comment]
I've got one of these in the tabs prototype I did – the tabs themselves are moving away from this design, but we can probably abstract this horizontal rule from it.

**Comment by MrDinsdale** [comment]
@joebell93 @aaronthomas We now have one of these in blackjack-guides-assets, probably needs a better name though.
