### ISSUE TITLE
Investigate extracting the `.is-active` indicator for panels from `c-tile`

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#114]
Active indicators for panels are currently limited to `c-tile`. 

How can we make this re-useable for other UI elements that trigger panels? A mixin? A utility class?

cc @romidane

**Comment by MrDinsdale** [comment]
I think the utility class would be fine.

**Comment by MrDinsdale** [comment]
toolkit-core - https://github.com/sky-uk/toolkit-core/pull/150
toolkit-ui - https://github.com/sky-uk/toolkit-ui/pull/187
toolkit - https://github.com/sky-uk/toolkit/pull/149

sky-pages - https://github.com/sky-uk/sky-pages/pull/2176
PPP - https://github.com/sky-uk/polaris-page-producer/pull/791
