### ISSUE TITLE
Tick for selection option dropdown not rendering properly on Safari

### ISSUE THREAD

**Issue by maxP-sky** [sky-uk/toolkit-ui#127]
`option` boxes within `select` in safari render either a huge tick or 2 dots.
When using toolkit class: .`c-form-select__dropdown`

Image based on Safari - Version 9.1.2 (10601.7.7)

![tick](https://cloud.githubusercontent.com/assets/15046615/18091015/17ea6ae6-6ebf-11e6-9c79-6ca5a9fc5af4.jpg)

**needs more detail**

**Comment by regularfry** [comment]
Compare the rendering on Chrome:

![screen shot 2016-08-30 at 14 09 39](https://cloud.githubusercontent.com/assets/39277/18092097/e267aaa6-6ec2-11e6-856b-7aaa57939bb3.png)

It *looks* like the glyph for the selection indicator is coded as a '...' in some fonts, but is a tick in the specific font Chrome is using for the drop-down.

**Comment by regularfry** [comment]
The description matches [here](http://stackoverflow.com/questions/31707365/two-dots-instead-of-checkmark-in-safari-select-options), but it's referring to an earlier safari version.

**Comment by MrDinsdale** [comment]
@regularfry Can't seem to recreate in Safari 9.1.3. Will have a little dig around and see what i can find

**Comment by joebell93** [comment]
@regularfry @maxP-sky can't seem to recreate this either, I'm going to suggest closing this for now until it pops up again elsewhere
