### ISSUE TITLE
Checkboxes don't handle multi-line labels

### ISSUE THREAD

**Issue by aaronthomas** [sky-uk/toolkit-ui#138]
## Expected Behavior
The tick icon should appear in the checkbox when selected. This is fine when the label only takes up one line, but not with multiple lines.

## Current Behavior
The tick icon appears _below_ the checkbox, and the checkbox simply becomes blue, without the icon.

## Possible Solution
I think this is related to the new positioning and display of the faux checkbox, but haven't explored much further at this stage.

## Steps to Reproduce (for bugs)
Create a checkbox with more than one line of label/caption text:

![screen shot 2016-09-09 at 11 05 06](https://cloud.githubusercontent.com/assets/1419558/18383929/be432848-767f-11e6-8f64-c064e054a0d2.png)

## Context
Many checkboxes across the Sky estate will require labels with longer copy than a single line. In my example, this is for a terms and conditions agreement in a payment form.

## Your Environment
Presumably affects most/all environments, but observed on the following:

* Version used: 0.5.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Latest Chrome
* Operating System and version (desktop or mobile): Mac

**Comment by aaronthomas** [comment]
In addition (and this probably needs clarifying with Design), but should the text wrap under the checkbox like it does? I think it would look better if the checkbox sat in it's own margin?

**Comment by joebell93** [comment]
I'll take a look at this now
