### ISSUE TITLE
Bug with Accordion Caret Icon in IE9

### ISSUE THREAD

**Issue by gpmcadamsky** [sky-uk/toolkit-ui#148]
The caret icon in IE9 for the accordion doesn't align vertically.

![image](https://cloud.githubusercontent.com/assets/17268999/18583882/4d0ed60a-7c05-11e6-935a-c084b86ea67e.png)

**Comment by joebell93** [comment]
@gpmcadamsky please can you re-write this issue using the template with some details/markup? Then we can look into it
