### ISSUE TITLE
Relative button borders don't display in Safari

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#152]
## Expected Behavior
Buttons should have a 1px border, a key feature of ghost buttons.

## Current Behavior
Safari doesn't seem to be displaying this when it's a relative value.

## Possible Solution
Increase the relative value or switch back to an absolute value until solved.

## Steps to Reproduce (for bugs)
Created in a simple blackjack toolbelt project.

As seen below:
![screen shot 2016-09-16 at 14 42 41](https://cloud.githubusercontent.com/assets/7349341/18587953/4a5c8774-7c1c-11e6-89bb-41c80d0c3664.png)

## Context
Borders should be visible around buttons.

## Your Environment
* Environment name and version: Safari 9.0.2
* Operating System and version: OSX El Capitan, Version 10.11.2

**Comment by MrDinsdale** [comment]
Yeah it looks like its rounding down the value incorrectly. Will have to rollback the changes.
