### ISSUE TITLE
Bottom Padding Non Existent on Select Boxes

### ISSUE THREAD

**Issue by StefanMcCready** [sky-uk/toolkit-ui#157]
## Expected Behaviour

There should be an equal amount of padding on the top and bottom of the content that is within the select box.

Having had to fix this within an app already, simple solution is to apply the correct padding.

## Current Behaviour

The padding the bottom doesn't match the padding at the top.

<img width="369" alt="screen shot 2016-09-20 at 13 04 38" src="https://cloud.githubusercontent.com/assets/14904083/18672431/0d30f6ba-7f40-11e6-8fac-01645f388523.png">

## Possible Solution

Apply bottom padding to match the top.

## Steps to Reproduce (for bugs)

Load page with select box on.

## Context

Just looks really weird.

## Your Environment

Toolkit UI Version: 0.5

Chrome Version: 53.0.2785.116 64-bit

**Comment by MrDinsdale** [comment]
I also see it in Chrome 53.0.2785.116 (64-bit), Safari seems fine, as does Firefox.

**Comment by MrDinsdale** [comment]
Also occurring on Sky Pages - Mobile Account section. (Chrome)

<img width="1353" alt="screen shot 2016-09-22 at 13 09 41" src="https://cloud.githubusercontent.com/assets/2472440/18747580/06c32672-80c6-11e6-90a9-13b65452ebb8.png">

**Comment by MrDinsdale** [comment]
Think it just needs `line-height: 1.2em;`

**Comment by joebell93** [comment]
Hmm line-height centers it but it's still lost the padding
