### ISSUE TITLE
Sky accessibility website - Header and footer

### ISSUE THREAD

**Issue by Mark-Nomensa** [sky-uk/toolkit-ui#163]
Hi Joe,

We are working on the Sky accessibility website refresh and using components from the toolkit.

Can you let me know what the plans are for the header and footer. Are you planning to make these part of the toolkit? And if so what is the timescale?

Thank you,
Mark

Senior Project Manager,
Nomensa

**Comment by joebell93** [comment]
Hi Mark,

The new header and footer are still very much WIP and I'm not sure of timescale. I'm also not sure whether they'll be included in the Toolkit or as a separate component that consumes the Toolkit (I suspect the latter). 

If it's essential to use the new header and footer I would suggest speaking to [Rob Leotta](mailto:robert.leotta@sky.uk), Head of UX.

However, I think it's likely you'll be asked to use the current legacy header and footer, for that I would suggest speaking to [Luke Barratt](mailto:luke.barratt@sky.uk), Software Engineer on how to implement this in your project.

If you do need to use the current legacy header and footer, you will need to manually import the [defence layer](https://github.com/sky-uk/toolkit-core/blob/master/utilities/_defence.scss) of our Toolkit Core to combat old styles.
