### ISSUE TITLE
Accessibility: Non-JS by default

### ISSUE THREAD

**Issue by csswizardry** [sky-uk/toolkit-ui#167]
We should ensure that any content that is revealed by JS (e.g. in dropdowns) is visible to users for whom JS isn’t available.
## Expected Behavior

When the page loads without JS, we should be able to see all accordions, dropdowns, etc. fully expanded.
## Current Behavior

Loading the page without JS keeps content hidden, with no way to access it.
## Context

It should not be assumed that JS is always available and loaded. Build for resilience.

**Comment by joebell93** [comment]
@csswizardry so would this be down to implementation rather than code we provide? 

Making sure people apply the `is-open` class by default, removing it in JS. Sounds more like a documentation problem
