### ISSUE TITLE
Make Core a dependency of this repo (UI)

### ISSUE THREAD

**Issue by csswizardry** [sky-uk/toolkit-ui#168]
In order for toolkit-ui to work at all, we _need_ to have toolkit-core present. We should allow consumers to install everything with a one-liner, rather than expecting them to install two things independently.

## Expected Behavior

I expect to be able to run:

```
$ npm install --save toolkit-ui
```

## Current Behavior

I currently have to run:

```
$ npm install --save toolkit-core
$ npm install --save toolkit-ui
```

## Possible Solution

Simply set `core` as a dependency of `ui`.

**Comment by joebell93** [comment]
I think we should still utilise 
```
$ npm install --save sky-toolkit
```
for the complete set, even if it is _kinda_ useless.

I think it would be a little clearer

**Comment by csswizardry** [comment]
I agree.
