### ISSUE TITLE
[Design] Update Tiles

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#191]
## Expected Behavior
- All Tiles should be **white** by default (only split tiles utilise a gradient)
- Collapsable tiles should move the image to one side.

## Current Behavior
- Tiles utilise a range of different background styles.
- Collapsable Tiles hide images.

**Comment by joebell93** [comment]
Did a couple of concepts for this a while back, but still waiting for design's confirmation on this

**Comment by apabbott** [comment]
Having a chat with Jon this afternoon. We can go through this then.

**Comment by joebell93** [comment]
Moved to https://github.com/sky-uk/toolkit/issues/179
