### ISSUE TITLE
Tooltip: c-tooltip--right doesn't work with c-tooltip--hover

### ISSUE THREAD

**Issue by kitation** [sky-uk/toolkit-ui#195]
Provide a general summary of the issue in the Title above

## Expected Behavior

If you're suggesting a change/improvement, tell us how it should work

## Current Behavior
Adding the c-tooltip--right class to the tooltip doesn't apply the styles if the c-tooltip--hover is present

## Attempted Fixes
What have you tried to resolve this issue?
What have you done to mitigate this problem within your own application?

## Steps to Reproduce (for bugs)
Provide a link to a live example, or an unambiguous set of steps to
reproduce this bug. Include code to reproduce, if relevant
```<div class="c-tooltip c-tooltip--hover c-tooltip--right">
  <button class="c-btn c-btn--primary c-tooltip__trigger">Trigger tooltip</button>
  <div class="c-tooltip__content">
      This is some text inside a tooltip.
  </div>
</div>

```
## Context
Needed to fix issue where tooltip for My Sky v2 My Details doesn't show correctly on mobile browsers

## Your Environment
Include as many relevant details about the environment you experienced the bug in

Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by joebell93** [comment]
Fixed by https://github.com/sky-uk/toolkit-ui/pull/201
