### ISSUE TITLE
Tiles: Text cut off on titles.

### ISSUE THREAD

**Issue by anevins12** [sky-uk/toolkit-ui#212]
Tile variations:
- Split Media Tile
- Full Tile
- Square
- Collapsible
- Other that inherit the above

## Expected Behavior
The tile should respond to the content and expand in height if necessary.

## Current Behavior
The tile cuts off the title if the title is too long or the resolution is too narrow.
![tile-cutoff](https://cloud.githubusercontent.com/assets/2318561/22590407/f294d150-ea06-11e6-9e71-4efd0d0440ce.png)

## Attempted Fixes
I haven't thoroughly tested this fix, but could the 'height' property be replaced with 'min-height'? The tile should then expand in height depending on the content, but the compromise is that the image can become cut-off for long titles.
![tile-cutoff-improvement](https://cloud.githubusercontent.com/assets/2318561/22590970/09440706-ea0a-11e6-9eea-051dc57505b3.png)

## Steps to Reproduce (for bugs)
https://www.sky.com/toolkit/components/tile
1. Edit the text via a web developer toolbar;
2 Replace the title with a long sentence to emulate the issue.

## Context
I'm extending the Split Media and Square variations of the Tile component and implementing into a CMS. The title of the Tile is content managed and there are cases where it is likely that long content will be used by the content editor. For example, Tiles used to represent a news article will use the news article title as the Title.

## Your Environment
Toolkit version: 1.0.2 - However the issue persists on the Sky.com/toolkit website.

Version used:
* Chrome newest.

**Comment by joebell93** [comment]
This seems to be a use-case example - changing the min-height affects the defined image and text height

You might need to just change the font size using a modifier or consider shortening the copy

**Comment by joebell93** [comment]
Closing as I didn't get a reply - I'd suggest using modifier on your Tile text (don't adjust the caption size as this goes against branding)

If you need a hand, drop me a message on Slack!
