### ISSUE TITLE
Line-height in Textarea query

### ISSUE THREAD

**Issue by anevins12** [sky-uk/toolkit-ui#214]
Component: Forms, Textarea.

Question: Is it intentional that the line height on this component appears large? Or is this a bug?

See attached screenshot for example.
![textarea-line-height](https://cloud.githubusercontent.com/assets/2318561/23067055/77a988f4-f515-11e6-828a-3c801ec56719.png)

As seen on sky.com/toolkit.

**Comment by joebell93** [comment]
Awesome thanks for finding, that's definitely a bug! Let us know how you get on
