### ISSUE TITLE
[Feature] Gradient Text

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#215]
## Context
More designs are cropping up with gradient-filled text

Could we provide mixins/components to support this?

**Comment by StefanMcCready** [comment]
There are know issues with browser support:

Need to make sure that autoprefixer only applies `-webkit-` prefix for the gradient as firefox is not capable of doing background clip.

**Comment by MrDinsdale** [comment]
We have mixins for this in https://github.com/sky-uk/sky-pages/blob/master/apps/mobile/stylesheets/tools/_mobile-mixins.scss

These allow us to add brand specific gradients and a mixin to add text gradients.

My personal opinion is that automatically generating classes for the gradients would add unnecessary weight to the toolkit. Perhaps this is however where the toolkit brand layers could come in, in mobile for example we have a number of gradients which are very specific and unlikely to be used elsewhere.

**Comment by joebell93** [comment]
On the autoprefixer issue, could we not just use `/* autoprefixer: off */` ?

**Comment by StefanMcCready** [comment]
You could do

**Comment by joebell93** [comment]
Moving to https://github.com/sky-uk/toolkit/issues/178
