### ISSUE TITLE
How should inputs share common styles?

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#32]
It would make sense to have a class for inputs to extend upon to share the common style (border, background etc.) but my concern is that this could become confusing when not used on all inputs (radio, checkbox etc.).

Should we use a class?

**Comment by MrDinsdale** [comment]
I'm not really sure there is any need for this (unless I'm misunderstanding) as it would just add more markup and not sure if it would have any advantage.

I think Toolkit should decide which input types should have specific styling applied to inputs etc with modifiers to adjust this. Variables can reduce repetition in the code etc if thats the goal.

**Comment by joebell93** [comment]
Agreed @MrDinsdale, probably worth closing this
