### ISSUE TITLE
`.c-form-inline` needs an IE fallback and displays incorrectly in Edge

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#64]
- We need a fallback (as `flex` is used) to ensure IE9+ compatibility.
- Appears on Edge as the following:

![Screenshot of c-form-inline in MS Edge](http://x16.imgup.net/ScreenShotde77.png)

**Comment by MrDinsdale** [comment]
This has been deprecated in favour of using in combo with the layout grid. A larger discussion needs to be had about accessibility and impacts
