### ISSUE TITLE
Accessibility `:focus` styles for Tiles

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#70]

**Comment by MrDinsdale** [comment]
This is addressed as part of the #86 fixes,

**Comment by MrDinsdale** [comment]
This needs some clarification from design regarding the best way to handle focus styling.

**Comment by joebell93** [comment]
After speaking with Dan, tiles should not have the focus effect that is currently present in sky-pages but instead be the same as hover
