### ISSUE TITLE
Provide vertical and horizontal center class in c-hero

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#74]
Example:

![Screenshot of watch page hero](http://s32.postimg.org/yold3mapx/Screen_Shot_2016_05_12_at_14_07_51.png)

**Comment by aaronthomas** [comment]
I think this would be better off as a vertical centering object/utility that can be used anywhere rather than something specific to hero components.

**Comment by MrDinsdale** [comment]
I think having this as a more general use utility is a good idea.

**Comment by MrDinsdale** [comment]
Added a PR for this utility in toolkit-core.

**Comment by MrDinsdale** [comment]
Utility added for vertical align in v0.3.14 of toolkit-core
