### ISSUE TITLE
Provide modifier class to specify alternative positions of c-hero__caption

### ISSUE THREAD

**Issue by rowlando** [sky-uk/toolkit-ui#77]
<img width="794" alt="screen shot 2016-05-16 at 16 16 54" src="https://cloud.githubusercontent.com/assets/89347/15293843/a6513436-1b81-11e6-8fc2-9738df3c09c6.png">

The TV logo and associated text can be seen as a few of things:

A. the hero's caption
B. a component in itself
C. part of the hero image (can't be part of image, as it needs to remain legible on small screens)

I think A is true, in which case, is it possible to provide a modifier to position `c-hero__caption` to position caption in the top right?

-----
**Channel Logo** - new UI component?
I think point B is also true as I've seen variations of it on lots of pages. If you agree, a Channel Logo component could be built into the toolkit - I could raise another issue to discuss the detail?

**Comment by MrDinsdale** [comment]
@rowlando This needs a little more debate internally to decide which elements we include for the toolkit. At present we are working from the designs Dan Bryson has been creating for the style guide and have been approaching this as an MVP for the toolkit.

We really need to decide how many variations of content modifiers we build in as adding too many is going to be extremely difficult to maintain going forward. We are currently working on better information on best practices for including custom modifiers for the toolkit for similar situations.

For now we don't want to develop elements which are out of the current style guide scope as it could very quickly lead to breaking changes down the line once/if they become part of the toolkit.

I would say as this differs substantially from the standard caption a new element would fit well such as `.c-hero__channel`. This would allow custom styling on top of toolkit without conflicts.

**Comment by joebell93** [comment]
After some discussion we've decided this isn't something that should be included in the Toolkit as it's a modification that could be made on a project-basis.

The focus of the Toolkit should be to provide a standard set of components rather than very specific requirements 🙂
