### ISSUE TITLE
Form dropdown IE styling issues

### ISSUE THREAD

**Issue by thomaslloyd** [sky-uk/toolkit-ui#78]
There are problems with the styling of the form dropdown in IE10/11 (IE9 seems ok). 

IE11:
![image](https://cloud.githubusercontent.com/assets/15194064/15320339/dfa3084e-1c27-11e6-9bbe-f3df93db3547.png)
IE10:
![image](https://cloud.githubusercontent.com/assets/15194064/15320367/fd0c16fa-1c27-11e6-9dbd-930a24b89491.png)
IE9:
![image](https://cloud.githubusercontent.com/assets/15194064/15320377/1d124fa0-1c28-11e6-9644-c7d72cadcaf8.png)

**Comment by joebell93** [comment]
Are you using the latest version? I believe @mrdinsdale fixed this

**Comment by thomaslloyd** [comment]
I think so, this is from the github.io toolkit page which @aaronthomas said he'd updated to use the newest version yesterday.

**Comment by joebell93** [comment]
How are you including the Toolkit in your project?

**Comment by thomaslloyd** [comment]
Importing in `package.json` here:

```
"sky-toolkit": "git+ssh://git@github.com:sky-uk/toolkit.git#v0.2.8",
```

This should point to the newest version of `toolkit-ui` and `toolkit-core` and then in our `global.scss` file importing `@import "~sky-toolkit-ui/all";` and `@import "~sky-toolkit-core/all";`.

**Comment by thomaslloyd** [comment]
Please could you point me to the code which fixed this. I can double check if it's getting into our compiled css file. :)

**Comment by joebell93** [comment]
Sure, pretty sure it's this 
https://github.com/sky-uk/toolkit-ui/pull/71

**Comment by thomaslloyd** [comment]
Strange, we definitely have that but I just cannot get it to work. There must be something stupidly simple I'm missing...

**Comment by thomaslloyd** [comment]
Would it be possible to update the toolkit github page so that it's working on there?

**Comment by aaronthomas** [comment]
@joebell93 can you please have a chat with @thomaslloyd in person about this tomorrow to sort this out in my absence.

**Comment by joebell93** [comment]
@mrdinsdale's back in the office so I'll ask if he can pick this back up

**Comment by MrDinsdale** [comment]
Should have a fix for this, going to double check and do a new PR.

**Comment by thomaslloyd** [comment]
Thanks @MrDinsdale!

**Comment by MrDinsdale** [comment]
#79 Should fix this

**Comment by MrDinsdale** [comment]
This should now be fixed in toolkit `v0.2.10` and toolkit-ui `v0.2.7`.

If you pull the latest it should work correctly, my apologies!

**Comment by thomaslloyd** [comment]
That's great! I'll close this issue now then. 👍

**Comment by MrDinsdale** [comment]
@thomaslloyd Did this fix the issues you were having?
