### ISSUE TITLE
Visual bugs in Safari 8.0

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#82]
Spotted by Paul Lemon

**Comment by joebell93** [comment]
- Arrows on panels not displaying 
- Select button icon not moving

**Comment by MrDinsdale** [comment]
@joebell93 Do you know if we have any VM set up anywhere with Safari 8.0 installed?

**Comment by vetrilad** [comment]
On safari 8 viewing http://sky-uk.github.io/toolkit/ 

![image](https://cloud.githubusercontent.com/assets/8461817/16986433/5c2717a6-4e7e-11e6-80f4-58ad46fd9823.png)
