### ISSUE TITLE
Visual bugs in Firefox 46.0.1

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#85]
- Some `.c-form` components show an outline, some don't
- `.c-form-select` doesn't hold the browser default dropdown arrow
- `.c-select` doesn't display the tick (seems to be an issue around the transform property)

**Comment by MrDinsdale** [comment]
@joebell93 is `.c-select` referring to the `c-form-checkbox`? This seems to only be an issue with using this method on radio. All browsers completely ignore the `::after` pseudo fake checkbox. Going to need another way to handle the radio boxes unless there is a way around it I haven't found yet.

**Comment by MrDinsdale** [comment]
Actually believe there may be an alternative way by tweaking the sibling selector.

**Comment by MrDinsdale** [comment]
Refactored to fix missing tick icon.
