### ISSUE TITLE
Tile refactor

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#86]
- [x] Reverse the collapsible functionality (collapse with a modifier instead)
- [x] Set `pointer-events: none;` on `c-shine-context `
- [x] Branded Tile hover text and background is inconsistent between focus / active
- [x] Links (without media and caption) should have a default hover state similar to the caption.
- [x] What's the purpose in adding a border of 5px at mobile?

Should we potentially rebuild from the ground up?

**Comment by MrDinsdale** [comment]
This going to be queued up on the `release/v0.3.0-tile-update` branch.

**Comment by MrDinsdale** [comment]
The 5px mobile styling was fixed to be more consistent as part of the collapsable refactor PR.

**Comment by MrDinsdale** [comment]
Merged
