### ISSUE TITLE
Button border scaling

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit-ui#90]
Buttons look really odd with a fixed value of `1px` when zoomed in, a relative value (e.g. `0.045em`) would look a lot nicer

**Comment by MrDinsdale** [comment]
Combining px values and em/rem values causes issues id say treat them all as px then convert. There may be a better way but in the past I've used this:

```
@function strip-unit($num) {
  @if type_of($num) == number {
    @return $num / ($num * 0 + 1);
  }

  @else {
    @warn "Value must be a number i.e. 12, 24px etc.";
  }
}
```

This gives a plain number without units. Then you can do the usual `value / base-font-size` and add the em units on.
