### ISSUE TITLE
Scaling issue with Shine on full-width tiles

### ISSUE THREAD

**Issue by pierrecoetzee** [sky-uk/toolkit-ui#95]
When using tiles for full-width content areas, the shine image scales and is cropped at the edge of `c-shine__rail` element. 

<img width="1177" alt="screen shot 2016-05-23 at 17 16 57" src="https://cloud.githubusercontent.com/assets/89347/15476967/3247ea10-210a-11e6-853d-97a6e7502452.png">

It should either be smaller or positioned lower.

**Comment by joebell93** [comment]
@pierrecoetzee thanks for raising this, please can you provide us your markup to look at?

**Comment by joebell93** [comment]
@pierrecoetzee please can you provide us your markup to look at?
What version of `sky-toolkit` are you using also?

**Comment by MrDinsdale** [comment]
Will try and look at refactoring the tile shine styling this week to prevent this issue.

**Comment by luca-baldelli2** [comment]
This is markup

```
<main class="o-container o-container--flush@small" role="main">
    <div class="o-layout">
        <div class="o-layout__item u-margin-top">
            <div class="c-tile">
                <div class="c-shine-context">
                    <div class="c-tile__content">
                        <div class="c-tile__body" style="background-color: #FFF;">
                            <div class="o-layout o-layout--center">
                                <div class="o-layout__item ">
                                    ...some content...
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="c-shine c-tile__shine c-tile__shine--top">
                        <div class="c-shine__rail"></div>
                    </div>
                    <div class="c-shine c-tile__shine c-tile__shine--bottom c-shine--rev">
                        <div class="c-shine__rail"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
```

At the moment we are using Sky Toolkit core v0.3.15 and Sky Toolkit UI v0.3.0.

**Comment by luca-baldelli2** [comment]
@MrDinsdale any chance getting this bug squashed within the next week or so?
