### ISSUE TITLE
Handling hover states on touch devices

### ISSUE THREAD

**Issue by MrDinsdale** [sky-uk/toolkit-ui#98]
This is a topic which requires some discussion as to whether or not this is a concern of toolkit and how we recommend addressing the issue.

Currently the approaches I can see as viable are:
- Create a separate toolkit add on for feature-detection which could be included to add support for libraries such as modernizr.
- Look at using css media feature queries, currently fairly unsupported however allows us to tackle feature detection in a way that is agnostic of the parent application.

Baking modernizr support into Toolkit directly isn't really an option in my opinion as it would no longer be platform agnostic. That being said creating overwriting hoverstates with additional css would potentially get quite messy.

**Comment by steveduffin** [comment]
I've put together a pull request with one proposal #122

**Comment by joebell93** [comment]
Gonna close this as it's gone a little stale. Let's raise an issue in https://github.com/sky-uk/toolkit if it's still a problem
